/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as OurVisionRouteImport } from './routes/our-vision'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SupabaseCheckRouteImport } from './routes/supabase-check'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAboutUsRouteImport } from './routes/admin.about-us'
import { Route as AdminAgentsRouteImport } from './routes/admin.agents'
import { Route as AdminCareersRouteImport } from './routes/admin.careers'
import { Route as AdminContactRouteImport } from './routes/admin.contact'
import { Route as AdminContactUsRouteImport } from './routes/admin.contact-us'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminEnquiriesRouteImport } from './routes/admin.enquiries'
import { Route as AdminFooterRouteImport } from './routes/admin.footer'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminSocialLinksRouteImport } from './routes/admin.social-links'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminVisionRouteImport } from './routes/admin.vision'
import { Route as AgentDashboardRouteImport } from './routes/agent.dashboard'
import { Route as AgentProfileRouteImport } from './routes/agent.profile'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const OurVisionRoute = OurVisionRouteImport.update({
  id: '/our-vision',
  path: '/our-vision',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SupabaseCheckRoute = SupabaseCheckRouteImport.update({
  id: '/supabase-check',
  path: '/supabase-check',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAboutUsRoute = AdminAboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCareersRoute = AdminCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactUsRoute = AdminContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFooterRoute = AdminFooterRouteImport.update({
  id: '/footer',
  path: '/footer',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSocialLinksRoute = AdminSocialLinksRouteImport.update({
  id: '/social-links',
  path: '/social-links',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVisionRoute = AdminVisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => AdminRoute,
} as any)
const AgentDashboardRoute = AgentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AgentRoute,
} as any)
const AgentProfileRoute = AgentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AgentRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact-us': typeof ContactUsRoute
  '/our-vision': typeof OurVisionRoute
  '/services': typeof ServicesRouteWithChildren
  '/supabase-check': typeof SupabaseCheckRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/about-us': typeof AdminAboutUsRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/contact-us': typeof AdminContactUsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/social-links': typeof AdminSocialLinksRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/vision': typeof AdminVisionRoute
  '/agent/dashboard': typeof AgentDashboardRoute
  '/agent/profile': typeof AgentProfileRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/account': typeof AccountRoute
  '/agent': typeof AgentRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact-us': typeof ContactUsRoute
  '/our-vision': typeof OurVisionRoute
  '/supabase-check': typeof SupabaseCheckRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/about-us': typeof AdminAboutUsRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/contact-us': typeof AdminContactUsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/social-links': typeof AdminSocialLinksRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/vision': typeof AdminVisionRoute
  '/agent/dashboard': typeof AgentDashboardRoute
  '/agent/profile': typeof AgentProfileRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact-us': typeof ContactUsRoute
  '/our-vision': typeof OurVisionRoute
  '/services': typeof ServicesRouteWithChildren
  '/supabase-check': typeof SupabaseCheckRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/about-us': typeof AdminAboutUsRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/contact-us': typeof AdminContactUsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/social-links': typeof AdminSocialLinksRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/vision': typeof AdminVisionRoute
  '/agent/dashboard': typeof AgentDashboardRoute
  '/agent/profile': typeof AgentProfileRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/account'
    | '/admin'
    | '/agent'
    | '/careers'
    | '/contact-us'
    | '/our-vision'
    | '/services'
    | '/supabase-check'
    | '/testimonials'
    | '/admin/about-us'
    | '/admin/agents'
    | '/admin/careers'
    | '/admin/contact'
    | '/admin/contact-us'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/enquiries'
    | '/admin/footer'
    | '/admin/services'
    | '/admin/social-links'
    | '/admin/testimonials'
    | '/admin/vision'
    | '/agent/dashboard'
    | '/agent/profile'
    | '/services/$slug'
    | '/admin/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/account'
    | '/agent'
    | '/careers'
    | '/contact-us'
    | '/our-vision'
    | '/supabase-check'
    | '/testimonials'
    | '/admin/about-us'
    | '/admin/agents'
    | '/admin/careers'
    | '/admin/contact'
    | '/admin/contact-us'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/enquiries'
    | '/admin/footer'
    | '/admin/services'
    | '/admin/social-links'
    | '/admin/testimonials'
    | '/admin/vision'
    | '/agent/dashboard'
    | '/agent/profile'
    | '/services/$slug'
    | '/admin'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/account'
    | '/admin'
    | '/agent'
    | '/careers'
    | '/contact-us'
    | '/our-vision'
    | '/services'
    | '/supabase-check'
    | '/testimonials'
    | '/admin/about-us'
    | '/admin/agents'
    | '/admin/careers'
    | '/admin/contact'
    | '/admin/contact-us'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/enquiries'
    | '/admin/footer'
    | '/admin/services'
    | '/admin/social-links'
    | '/admin/testimonials'
    | '/admin/vision'
    | '/agent/dashboard'
    | '/agent/profile'
    | '/services/$slug'
    | '/admin/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgentRoute: typeof AgentRouteWithChildren
  CareersRoute: typeof CareersRoute
  ContactUsRoute: typeof ContactUsRoute
  OurVisionRoute: typeof OurVisionRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SupabaseCheckRoute: typeof SupabaseCheckRoute
  TestimonialsRoute: typeof TestimonialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-vision': {
      id: '/our-vision'
      path: '/our-vision'
      fullPath: '/our-vision'
      preLoaderRoute: typeof OurVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supabase-check': {
      id: '/supabase-check'
      path: '/supabase-check'
      fullPath: '/supabase-check'
      preLoaderRoute: typeof SupabaseCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/about-us': {
      id: '/admin/about-us'
      path: '/about-us'
      fullPath: '/admin/about-us'
      preLoaderRoute: typeof AdminAboutUsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/careers': {
      id: '/admin/careers'
      path: '/careers'
      fullPath: '/admin/careers'
      preLoaderRoute: typeof AdminCareersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact-us': {
      id: '/admin/contact-us'
      path: '/contact-us'
      fullPath: '/admin/contact-us'
      preLoaderRoute: typeof AdminContactUsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/footer': {
      id: '/admin/footer'
      path: '/footer'
      fullPath: '/admin/footer'
      preLoaderRoute: typeof AdminFooterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/social-links': {
      id: '/admin/social-links'
      path: '/social-links'
      fullPath: '/admin/social-links'
      preLoaderRoute: typeof AdminSocialLinksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vision': {
      id: '/admin/vision'
      path: '/vision'
      fullPath: '/admin/vision'
      preLoaderRoute: typeof AdminVisionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/agent/dashboard': {
      id: '/agent/dashboard'
      path: '/dashboard'
      fullPath: '/agent/dashboard'
      preLoaderRoute: typeof AgentDashboardRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/profile': {
      id: '/agent/profile'
      path: '/profile'
      fullPath: '/agent/profile'
      preLoaderRoute: typeof AgentProfileRouteImport
      parentRoute: typeof AgentRoute
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAboutUsRoute: typeof AdminAboutUsRoute
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminCareersRoute: typeof AdminCareersRoute
  AdminContactRoute: typeof AdminContactRoute
  AdminContactUsRoute: typeof AdminContactUsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminFooterRoute: typeof AdminFooterRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSocialLinksRoute: typeof AdminSocialLinksRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminVisionRoute: typeof AdminVisionRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAboutUsRoute: AdminAboutUsRoute,
  AdminAgentsRoute: AdminAgentsRoute,
  AdminCareersRoute: AdminCareersRoute,
  AdminContactRoute: AdminContactRoute,
  AdminContactUsRoute: AdminContactUsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminFooterRoute: AdminFooterRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSocialLinksRoute: AdminSocialLinksRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminVisionRoute: AdminVisionRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AgentRouteChildren {
  AgentDashboardRoute: typeof AgentDashboardRoute
  AgentProfileRoute: typeof AgentProfileRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentDashboardRoute: AgentDashboardRoute,
  AgentProfileRoute: AgentProfileRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AgentRoute: AgentRouteWithChildren,
  CareersRoute: CareersRoute,
  ContactUsRoute: ContactUsRoute,
  OurVisionRoute: OurVisionRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SupabaseCheckRoute: SupabaseCheckRoute,
  TestimonialsRoute: TestimonialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
